# Generated by Django 4.2.16 on 2024-11-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staf',
            options={'default_permissions': 'view', 'permissions': (('add_staf', 'Can add staf'), ('change_staf', 'Can change staf'), ('del_staf', 'Can del staf'))},
        ),
    ]
